# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Category.create!(name: 'Ropa')
Category.create!(name: 'Alimentos')
Category.create!(name: 'Calzado')
Category.create!(name: 'Muebles')
Category.create!(name: 'Deportes')
Category.create!(name: 'Aretes')
Category.create!(name: 'Programas')
Category.create!(name: 'Antiguedades')
Category.create!(name: 'Articulos')
Category.create!(name: 'Libros')
Category.create!(name: 'Aplicaciones')
Category.create!(name: 'Accesorios')
Category.create!(name: 'Armas')
Category.create!(name: 'Astillas')
Category.create!(name: 'Vestidos')
Category.create!(name: 'Multiples')
Category.create!(name: 'Capacitacion')
Category.create!(name: 'Estrellas')
Category.create!(name: 'Random')
Category.create!(name: 'Mix')
Category.create!(name: 'Estadios')
Category.create!(name: 'Futbol')
Category.create!(name: 'Deportes')
Category.create!(name: 'Superheroes')
Category.create!(name: 'Comunicacion')
Category.create!(name: 'Herramientas')
Category.create!(name: 'Ingenieria')
Category.create!(name: 'Play Station')
Category.create!(name: 'Videos')
Category.create!(name: 'Camaras')
Category.create!(name: 'Pruebas')
Category.create!(name: 'Estoy en eso')
Category.create!(name: 'Jeffrey')